services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.9.0'
    container_name: elasticsearch
    environment:
      # - 'ELASTIC_PASSWORD=admin'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'

  kibana:
    image: 'docker.elastic.co/kibana/kibana:8.9.0'
    container_name: kibana
    ports:
      - '5601:5601'